services:
  mongo_db:
    container_name: mongo_db
    restart: unless-stopped
    image: mongo
    volumes:
       - mongo-data:/data/db
       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: DzzpKlcbnsSLewlsMVakQ5
      MONGO_INITDB_DATABASE: admin

    ports:
      - "27017:27017"

    # networks:
    #   - winguid-network-prod
  
        
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: housing-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - mongo_db
   

volumes:
  mongo-data:
